#include "sae_par.h"
#include "aryk1.h"
#include "mers.h"
#include "aryk_err.h"
#include "dat_par.h"

void arykNewp( const char *ftype, int ndim, const hdsdim *ubnd,
              AryPlace **place, Ary **ary, int *status ) {
/*
*+
*  Name:
*     arykNewp

*  Purpose:
*     Create a new primitive array.

*  Synopsis:
*     void arykNewp( const char *ftype, int ndim, const hdsdim *ubnd,
*                   AryPlace **place, Ary **ary, int *status )

*  Description:
*     This function creates a new primitive array and returns an
*     identifier for it. The array may subsequently be manipulated with
*     other Ary routines.

*  Parameters:
*     ftype
*        Data type of the array (e.g. '_REAL'). Note that complex types
*        are not allowed for primitive arrays.
*     ndim
*        Number of array dimensions.
*     ubnd
*        Upper pixel-index bounds of the array (the lower bound of each
*        dimension is taken to be 1).
*     place
*        On entry, holds an array placeholder (e.g. generated by the
*        arykPlace function) which indicates the position in the data
*        system where the new array will reside. The placeholder is
*        annulled by this function, and a value of NULL will be returned
*        on exit.
*     ary
*         Returned holding an identifier for the new array.
*     status
*        The global status.

*  Notes:
*     -  If this routine is called with "status" set, then a value of
*     NULL will be returned for the "ary" argument, although no
*     further processing will occur. The same value will also be
*     returned if the routine should fail for any reason. In either
*     event, the placeholder will still be annulled.

*  Copyright:
*      Copyright (C) 2017 East Asian Observatory
*      All rights reserved.

*  Licence:
*     This program is free software; you can redistribute it and/or
*     modify it under the terms of the GNU General Public License as
*     published by the Free Software Foundation; either version 2 of
*     the License, or (at your option) any later version.
*
*     This program is distributed in the hope that it will be
*     useful,but WITHOUT ANY WARRANTY; without even the implied
*     warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
*     PURPOSE. See the GNU General Public License for more details.
*
*     You should have received a copy of the GNU General Public License
*     along with this program; if not, write to the Free Software
*     Foundation, Inc., 51 Franklin Street,Fifth Floor, Boston, MA
*     02110-1301, USA

*  Authors:
*     RFWS: R.F. Warren-Smith (STARLINK)
*     DSB: David S. Berry (EAO)

*  History:
*     03-JUL-2017 (DSB):
*        Original version, based on equivalent Fortran routine by RFWS.

*-
*/

/* Local variables: */
   AryACB *acb;               /* Pointer to the ACB */
   AryDCB *dcb;               /* Pointer to the DCB */
   AryPCB *pcb;               /* Pointer to the PCB */
   char vtype[ARYK__SZTYP+1];  /* Numeric type of the array */
   hdsdim lbnd[ARYK__MXDIM];   /* Lower bounds of array */
   int cmplx;                 /* Whether a complex array is required */
   int erase;                 /* Whether to erase placeholder object */
   int i;                     /* Loop counter for dimensions */
   int ndim0;                 /* Usable number of dimensions */
   int tstat;                 /* Temporary status variable */

/* Set an initial value for the IARY argument. */
   *ary = NULL;

/* Save the STATUS value and mark the error stack. */
   tstat = *status;
   errMark();

/* Import the array placeholder, converting it to a PCB pointer. */
   *status = SAI__OK;
   pcb = (AryPCB *) aryk1Impid( *place, 0, 0, 0, status );

/* If there has been no error at all so far, then check the full type
   specification for validity. */
   if( ( *status == SAI__OK ) && ( tstat == SAI__OK ) ){
      aryk1Vftp( ftype, sizeof(vtype), vtype, &cmplx, status );

/* If the type is complex, then report an error. */
      if( cmplx ){
         *status = ARYK__FTPIN;
         msgSetc( "B", ftype );
         errRep( " ", "The complex type '^B' is not valid for a primitive"
                 "array (possible programming error).", status );
      }

/* Check the array upper bounds for validity. */
      if( *status == SAI__OK ){
         ndim0 = ( ndim < ARYK__MXDIM ) ? ndim : ARYK__MXDIM;
         for( i = 0; i < ndim0; i++ ) lbnd[ i ] = 1;
         aryk1Vbnd( ndim, lbnd, ubnd, status );

/* Create a new simple array structure in place of the placeholder object,
   obtaining a DCB entry which refers to it. */
         if( *status == SAI__OK ){
            aryk1Dcrep( 0, vtype, ndim, ubnd, pcb->tmp, &pcb->loc,
                       &dcb, status );
         }
      }

/* Create a base array entry in the ACB to refer to the DCB entry. */
      aryk1Crnba( dcb, &acb, status );

/* Export an identifier for the array. */
      *ary = aryk1Expid( (AryObject *) acb, status );
   }

/* Annul the placeholder, erasing the associated object if any error has
   occurred. */
   if( pcb ){
      erase = ( *status != SAI__OK ) || ( tstat != SAI__OK );
      aryk1Annpl( erase, &pcb, status );
   }

/* Reset the PLACE argument. */
   *place = NULL;

/* Annul any error if STATUS was previously bad, otherwise let the new
   error report stand. */
   if( *status != SAI__OK ){
      if( tstat != SAI__OK ){
         errAnnul( status );
         *status = tstat;

/* If appropriate, report the error context and call the error tracing
   routine. */
      } else {
         *ary = NULL;
         errRep( " ", "arykNewp: Error creating a new primitive array.",
                 status );
         aryk1Trace( "arykNewp", status );
      }
   } else {
      *status = tstat;
   }

/* Release error stack. */
   errRlse();

}
